Repository Four-Talking/Nateam, pull requests merged in 2023-12, with the labels that each got.

#1 Design: 엔티티 설계 및 구현
  src/main/java/fourtalking/Nateam/cartgame/entity/CartGame.java
  src/main/java/fourtalking/Nateam/game/entity/Game.java
  src/main/java/fourtalking/Nateam/order/entity/Order.java
  src/main/java/fourtalking/Nateam/orderGame/entity/OrderGame.java
  src/main/java/fourtalking/Nateam/review/entity/Review.java
  src/main/java/fourtalking/Nateam/user/constant/UserRole.java
  src/main/java/fourtalking/Nateam/user/entity/User.java
Labels: enhancement

#6 Fix: Order 테이블 이름을 Orders로 변경
  src/main/java/fourtalking/Nateam/order/entity/Orders.java
Labels: bug

#12 Fix: Review 테이블 userId 추가
  src/main/java/fourtalking/Nateam/review/entity/Review.java
Labels: bug

#14 Feature: 게임 단건 조회 API 기능 구현
  src/main/java/fourtalking/Nateam/game/controller/GameController.java
  src/main/java/fourtalking/Nateam/game/dto/GameGetDTO.java
  src/main/java/fourtalking/Nateam/game/service/GameService.java
Labels: enhancement

#16 Feature: 리뷰 등록 API 기능 구현
  src/main/java/fourtalking/Nateam/global/exception/common/ErrorCode.java
  src/main/java/fourtalking/Nateam/global/exception/review/ReviewNotFoundException.java
  src/main/java/fourtalking/Nateam/review/controller/ReviewController.java
  src/main/java/fourtalking/Nateam/review/dto/ReviewRegisterDTO.java
  src/main/java/fourtalking/Nateam/review/repository/ReviewRepository.java
  src/main/java/fourtalking/Nateam/review/service/ReviewService.java
Labels: enhancement

#19 Feature: 게임 전체 목록 조회 API 기능 구현
  src/main/java/fourtalking/Nateam/game/controller/GameController.java
  src/main/java/fourtalking/Nateam/game/repositroy/GameRepository.java
  src/main/java/fourtalking/Nateam/game/service/GameService.java
Labels: enhancement

#20 Feature: 리뷰 단건 조회 기능 API 구현
  src/main/java/fourtalking/Nateam/review/controller/ReviewController.java
  src/main/java/fourtalking/Nateam/review/dto/GetReviewDTO.java
  src/main/java/fourtalking/Nateam/review/dto/ReviewRegisterDTO.java
  src/main/java/fourtalking/Nateam/review/service/ReviewService.java
Labels: enhancement

#40 Refactor: 모든 리뷰 User 기능 추가 및 리뷰 ResponseDTO 순서 변경
  src/main/java/fourtalking/Nateam/global/exception/common/ErrorCode.java
  src/main/java/fourtalking/Nateam/global/exception/review/InconsistencyUserIdException.java
  src/main/java/fourtalking/Nateam/review/controller/ReviewController.java
  src/main/java/fourtalking/Nateam/review/dto/GetReviewDTO.java
  src/main/java/fourtalking/Nateam/review/dto/ReviewRegisterDTO.java
  src/main/java/fourtalking/Nateam/review/dto/UpdateReviewDTO.java
  src/main/java/fourtalking/Nateam/review/service/ReviewService.java
Labels: enhancement

#42 Feature: 게임 수정 API 기능 구현
  src/main/java/fourtalking/Nateam/game/controller/GameController.java
  src/main/java/fourtalking/Nateam/game/dto/GameModifyDTO.java
  src/main/java/fourtalking/Nateam/game/entity/Game.java
  src/main/java/fourtalking/Nateam/game/service/GameService.java
Labels: enhancement

#44 Fix: ErrorCode 32라인 ; -> , 으로 변경
  src/main/java/fourtalking/Nateam/global/exception/common/ErrorCode.java
Labels: bug

#48 Refactor: 리뷰 DTO User객체 전달 -> UserName만 전달로 변경
  src/main/java/fourtalking/Nateam/review/dto/GetReviewDTO.java
  src/main/java/fourtalking/Nateam/review/dto/ReviewRegisterDTO.java
  src/main/java/fourtalking/Nateam/review/dto/UpdateReviewDTO.java
  src/main/java/fourtalking/Nateam/review/service/ReviewService.java
Labels: enhancement

#51 Feature: 게임 삭제 API 기능 구현
  src/main/java/fourtalking/Nateam/game/controller/GameController.java
  src/main/java/fourtalking/Nateam/game/service/GameService.java
Labels: enhancement

#60 feature:장바구니 모두 삭제 메소드 추가
  src/main/java/fourtalking/Nateam/cartgame/repository/CartGameRepository.java
  src/main/java/fourtalking/Nateam/cartgame/service/CartGameService.java
Labels: enhancement

#67 Fix: 게임 단건 조회 - 게임 소개에 이름 소개가 담겨 반환
  src/main/java/fourtalking/Nateam/game/dto/GameGetDTO.java
Labels: bug

#70 Chore: 테스트를 위한 yml 파일 설정
  src/test/resources/application.yml
Labels: documentation, enhancement

#72 Fix: 게임이 없을 때 리뷰가 등록되는 버그수정
  src/main/java/fourtalking/Nateam/review/service/ReviewService.java
Labels: bug

#73 Fix: User 테이블 이름을 Users로 변경
  src/main/java/fourtalking/Nateam/user/entity/User.java
Labels: bug

#74 Feature: review 등록 테스트 API 구현
  src/main/java/fourtalking/Nateam/review/service/ReviewService.java
  src/test/java/fourtalking/Nateam/review/service/ReviewServiceTest.java
  src/test/java/fourtalking/Nateam/test/CommonTest.java
Labels: enhancement

#77 Feature: 리뷰 조회 Test 기능 API 개발
  src/test/java/fourtalking/Nateam/review/service/ReviewServiceTest.java
Labels: enhancement

#79 Feature: 리뷰 전체 조회 서비스 테스트
  src/test/java/fourtalking/Nateam/review/service/ReviewServiceTest.java
Labels: enhancement

#83 Feature: 리뷰 삭제 서비스 테스트
  src/test/java/fourtalking/Nateam/review/service/ReviewServiceTest.java
Labels: enhancement

#85 Fix: GameService와 ReviewService의 순환참조 해결
  src/main/java/fourtalking/Nateam/game/repositroy/GameRepository.java
  src/main/java/fourtalking/Nateam/game/service/GameService.java
Labels: Fix

#92 test: 게임 작성, 조회, 수정, 삭제 테스트
  src/test/java/fourtalking/Nateam/game/service/GameServiceTest.java
  src/test/java/fourtalking/Nateam/test/GameTest.java
Labels: test

#93 Refactor: 게임 등록, 수정 응답 값에 게임 Id 필드 추가
  src/main/java/fourtalking/Nateam/game/dto/GameModifyDTO.java
  src/main/java/fourtalking/Nateam/game/dto/GameRegisterDTO.java
Labels: enhancement

#101 Test : 장바구니 수정,조회,삭제 테스트
  src/test/java/fourtalking/Nateam/cartgame/service/CartGameServiceTest.java
Labels: test
